### ISSUE TITLE
syntax error: unexpected token

### ISSUE THREAD

**Issue by zaaakk** [CesiumGS/gltf-pipeline#546]
Can't use the compressor at all because of this error
after attempting to convert glb to gltf:
`SyntaxError: Unexpected token {
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gltf-pipeline/node_modules/fs-extra/lib/mkdirs/index.js:3:44)`

after attempting to compress glb:

`$ npx gltf-pipeline -i file.glb -d --draco.compressionLevel 10 -o compressed.glb
Unexpected token {
`

**Comment by lilleyse** [comment]
@zaaakk I'm not seeing this error. What version of Node are you using?

**Comment by liuyu-struggle** [comment]
Hello, has this problem been solved? I also have the same problem. My node version is 8.11.4

**Comment by liuyu-struggle** [comment]
![image](https://user-images.githubusercontent.com/37584392/93197050-c4073200-f77d-11ea-96f3-465b10474669.png)

**Comment by liuyu-struggle** [comment]
@zaaakk @lilleyse

**Comment by lilleyse** [comment]
@liuyu-struggle could you try the latest Node 12 release? https://nodejs.org/dist/latest-v12.x/
