### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by mikejernil** [CesiumGS/gltf-pipeline#548]
Getting this error in a nodejs server running gltf-pipeline to DRACO compress glb models. This specific error is thrown for only one specific model. What could this be related to? 

`Error
    at new RuntimeError (/opt/node-compress-model1/node_modules/cesium/Build/CesiumUnminified/Cesium.js:6666:13)
    at /opt/node-compress-model1/node_modules/gltf-pipeline/lib/compressDracoMeshes.js:186:23
    at Function.ForEach.meshPrimitive (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/ForEach.js:235:27)
    at /opt/node-compress-model1/node_modules/gltf-pipeline/lib/compressDracoMeshes.js:101:17
    at Function.ForEach.object (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/ForEach.js:45:27)
    at Function.ForEach.topLevel (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/ForEach.js:64:20)
    at Function.ForEach.mesh (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/ForEach.js:226:20)
    at compressDracoMeshes (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/compressDracoMeshes.js:100:13)
    at /opt/node-compress-model1/node_modules/gltf-pipeline/lib/processGltf.js:65:16
    at tryCatcher (/opt/node-compress-model1/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/opt/node-compress-model1/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/opt/node-compress-model1/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/opt/node-compress-model1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/node-compress-model1/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/opt/node-compress-model1/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/opt/node-compress-model1/node_modules/bluebird/js/release/promise.js:649:10) {
  name: 'RuntimeError',
  message: 'Error: Draco encoding failed.',
  stack: 'Error\n' +
    '    at new RuntimeError (/opt/node-compress-model1/node_modules/cesium/Build/CesiumUnminified/Cesium.js:6666:13)\n' +
    '    at /opt/node-compress-model1/node_modules/gltf-pipeline/lib/compressDracoMeshes.js:186:23\n' +
    '    at Function.ForEach.meshPrimitive (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/ForEach.js:235:27)\n' +
    '    at /opt/node-compress-model1/node_modules/gltf-pipeline/lib/compressDracoMeshes.js:101:17\n' +
    '    at Function.ForEach.object (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/ForEach.js:45:27)\n' +
    '    at Function.ForEach.topLevel (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/ForEach.js:64:20)\n' +
    '    at Function.ForEach.mesh (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/ForEach.js:226:20)\n' +
    '    at compressDracoMeshes (/opt/node-compress-model1/node_modules/gltf-pipeline/lib/compressDracoMeshes.js:100:13)\n' +
    '    at /opt/node-compress-model1/node_modules/gltf-pipeline/lib/processGltf.js:65:16\n' +
    '    at tryCatcher (/opt/node-compress-model1/node_modules/bluebird/js/release/util.js:16:23)\n' +
    '    at Object.gotValue (/opt/node-compress-model1/node_modules/bluebird/js/release/reduce.js:166:18)\n' +
    '    at Object.gotAccum (/opt/node-compress-model1/node_modules/bluebird/js/release/reduce.js:155:25)\n' +
    '    at Object.tryCatcher (/opt/node-compress-model1/node_modules/bluebird/js/release/util.js:16:23)\n' +
    '    at Promise._settlePromiseFromHandler (/opt/node-compress-model1/node_modules/bluebird/js/release/promise.js:547:31)\n' +
    '    at Promise._settlePromise (/opt/node-compress-model1/node_modules/bluebird/js/release/promise.js:604:18)\n' +
    '    at Promise._settlePromise0 (/opt/node-compress-model1/node_modules/bluebird/js/release/promise.js:649:10)'
}`

**Comment by lilleyse** [comment]
@mikejernil This might be an error in the draco library itself. Could you post the glTF here so we can confirm?

**Comment by mikejernil** [comment]
@lilleyse The files are for a private client. Can I send it to you by mail?

**Comment by mikejernil** [comment]
@lilleyse I saw your response in the other issue. I ave mailed the glb file to https://github.com/CesiumGS/gltf-pipeline/issues/548 . Please take a look and let me know.
