### ISSUE TITLE
Error: Draco encoding failed.

### ISSUE THREAD

**Issue by josh-wheeler-arup** [CesiumGS/gltf-pipeline#549]
Error when trying to run a Draco compression on a large(ish) gltf file (60mb).

`node node_modules/gltf-pipeline/bin/gltf-pipeline.js -i data/biggertest.gltf -o data/draco.gltf -d=true --draco.compressionLevel=10 --stats

Error
    at new RuntimeError (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/cesium/Build/CesiumUnminified/Cesium.js:6788:13)
    at /home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/gltf-pipeline/lib/compressDracoMeshes.js:186:23
    at Function.ForEach.meshPrimitive (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/gltf-pipeline/lib/ForEach.js:235:27)
    at /home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/gltf-pipeline/lib/compressDracoMeshes.js:101:17
    at Function.ForEach.object (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/gltf-pipeline/lib/ForEach.js:45:27)
    at Function.ForEach.topLevel (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/gltf-pipeline/lib/ForEach.js:64:20)
    at Function.ForEach.mesh (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/gltf-pipeline/lib/ForEach.js:226:20)
    at compressDracoMeshes (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/gltf-pipeline/lib/compressDracoMeshes.js:100:13)
    at /home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/gltf-pipeline/lib/processGltf.js:65:16
    at tryCatcher (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/josh/development/cern-dt/cern-dt-api-ifc/node_modules/bluebird/js/release/promise.js:649:10) {
  message: 'Error: Draco encoding failed.'
}`

At first I thought it was a user error, but I was able to successfully compress other gltf files found on the Khronos group sample models repo.

Some context about the gtlf... the gltf file is generated from a pipeline that converts an .IFC file -> .OBJ -> .gLTF using IfcConvert (IfcOpenshell) and obj2gltf. The output .gLTF file has been run through the [Khronos group validator (https://github.khronos.org/glTF-Validator/) and no errors were picked up. So everything seems ok with the gLTF itself. I'm wondering if this is an issue with the draco mesh lib rather than gltf-pipeline? Any information would be greatly appreciated.

**Comment by lilleyse** [comment]
> I'm wondering if this is an issue with the draco mesh lib rather than gltf-pipeline?

It's possible, especially if other models were working. Are you able to share the glTF so we can confirm?

**Comment by josh-wheeler-arup** [comment]
Is there any way to privately send you the file? I'm working with a private client, so it would be great not to publicly expose the gltf.

**Comment by lilleyse** [comment]
@josh-wheeler-arup you can send it to support@cesium.com.

CC @OmarShehata

**Comment by josh-wheeler-arup** [comment]
ok, I've sent that through. Thanks for the promptness @lilleyse ! Much appreciated

**Comment by lilleyse** [comment]
@josh-wheeler-arup interestingly it does not fail with the default compression level of 7.

**Comment by josh-wheeler-arup** [comment]
@lilleyse hmm strange. I just tried running it again with the default level (just a -d flag) and it still doesn't work for me. I'm still getting the `message: 'Error: Draco encoding failed.'` error message.

**Comment by josh-wheeler-arup** [comment]
@lilleyse just checking if you have any further updates on this issue?

**Comment by lilleyse** [comment]
@josh-wheeler-arup sorry no updates yet

**Comment by hamzakhuswan** [comment]
@lilleyse I have the same issue any update yet? 

I am converting a glb file to gltf, then trying to converting to it to draco gltf. But is there where I see the same error that is above.

I am using this as command line tool, on windows.

**Comment by lilleyse** [comment]
@josh-wheeler-arup @hamzakhuswan 

Often the cause of the problem is models with very small or degenerate triangles. There's not much we can do from the gltf-pipeline side. You might have more luck opening an issue in https://github.com/google/draco/.
