### ISSUE TITLE
Error: No valid exports main found for gltf-pipeline/node_modules/cesium

### ISSUE THREAD

**Issue by Christopher-Hayes** [CesiumGS/gltf-pipeline#554]
Getting this error when I try to run `gltf-pipeline`.

```
$ gltf-pipeline

internal/modules/cjs/loader.js:614
  throw e;
  ^

Error: No valid exports main found for '/home/chris/.nvm/versions/node/v13.2.0/lib/node_modules/gltf-pipeline/node_modules/cesium'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/home/chris/.nvm/versions/node/v13.2.0/lib/node_modules/gltf-pipeline/bin/gltf-pipeline.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1121:30) {
  code: 'MODULE_NOT_FOUND'
```
**Versions:**
Node: v13.2.0
NPM: v6.14.5
OS: Ubuntu 20.04 LTS

I only just installed `gltf-pipeline`, NPM seemed to install without issue:

```
$ npm install -g gltf-pipeline
/home/chris/.nvm/versions/node/v13.2.0/bin/gltf-pipeline -> /home/chris/.nvm/versions/node/v13.2.0/lib/node_modules/gltf-pipeline/bin/gltf-pipeline.js
+ gltf-pipeline@3.0.0
added 38 packages from 19 contributors in 6.326s
```

Should I look into trying to install this cesium module?

**Comment by lilleyse** [comment]
@Christopher-Hayes can you try a newer version of Node? I get the same error in 13.2.0 but not in 13.7.0 or above.

**Comment by Christopher-Hayes** [comment]
Upgrading to 13.7.0 fixed it, thanks!
