### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by sui0312feng** [CesiumGS/gltf-pipeline#646]
[Uploading NO_0.zip…]()
RuntimeError: memory access out of bounds
    at wasm://wasm/0016da02:wasm-function[428]:0x43171
    at wasm://wasm/0016da02:wasm-function[423]:0x42d9a
    at wasm://wasm/0016da02:wasm-function[446]:0x4372f
    at a._emscripten_bind_Encoder_EncodeMeshToDracoBuffer_2 (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\node_modules\draco3d\draco_encoder_nodejs.js:58:229)
    at y.EncodeMeshToDracoBuffer.y.EncodeMeshToDracoBuffer (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\node_modules\draco3d\draco_encoder_nodejs.js:92:85)
    at D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:264:37
    at ForEach.meshPrimitive (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\lib\ForEach.js:239:21)
    at D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:143:13
    at ForEach.object (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\lib\ForEach.js:44:21)
    at ForEach.topLevel (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\lib\ForEach.js:63:18)
    at ForEach.mesh (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\lib\ForEach.js:230:18)
    at compress (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:142:11)
    at D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\lib\compressDracoMeshes.js:59:14
    at tryCatcher (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\Program Files\nodejs\node_global\node_modules\gltf-pipeline\node_modules\bluebird\js\release\promise.js:604:18)

**Comment by Ben-Mack** [comment]
I'm having the same memory access out of bounds problem, @sui0312feng have you found the solution for this?
